version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    networks:
      - app-network

  frontend-app:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:3100"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G
  
  frontend-tests:
    restart: always
    build:
      context: ./frontend/tests
      dockerfile: Dockerfile
    depends_on:
      - frontend-app
    networks:
      - app-network 
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G
    volumes:
      - ./artifacts:/test-results
    
    
networks:
  app-network:
    driver: bridge
